"""Core package exports for the mutual_concept_loss project."""

from .data import (
    DEFAULT_PRIMITIVES,
    GeneratorConfig,
    GroupedBatchSampler,
    PrimitiveContext,
    PrimitiveDefinition,
    PrimitiveInstance,
    SyntheticTaskDataset,
    SyntheticTaskGenerator,
)
from .losses import (
    LossManager,
    LossSchedule,
    SparseAutoencoderLoss,
    SharedSubspaceLoss,
    TaskLoss,
)
from .models import (
    ConvGridDecoder,
    ConvGridEncoder,
    LinearAdapter,
    SharedAutoencoderModel,
    SharedBottleneck,
    SparseAutoencoder,
)
from .training import (
    CheckpointConfig,
    CosineWarmupSchedulerConfig,
    EvaluationDataConfig,
    FewShotConfig,
    FewShotDataConfig,
    FewShotResult,
    LoggingConfig,
    OptimizerConfig,
    TrainingConfig,
    Trainer,
    build_cosine_warmup_scheduler,
    build_few_shot_loaders,
    build_zero_shot_dataloader,
    evaluate_loop,
    run_few_shot_adaptation,
)
from .utils.seed import set_seed

__all__ = [
    "DEFAULT_PRIMITIVES",
    "GeneratorConfig",
    "GroupedBatchSampler",
    "PrimitiveContext",
    "PrimitiveDefinition",
    "PrimitiveInstance",
    "SyntheticTaskDataset",
    "SyntheticTaskGenerator",
    "LossManager",
    "LossSchedule",
    "SparseAutoencoderLoss",
    "SharedSubspaceLoss",
    "TaskLoss",
    "ConvGridDecoder",
    "ConvGridEncoder",
    "LinearAdapter",
    "SharedAutoencoderModel",
    "SharedBottleneck",
    "SparseAutoencoder",
    "CheckpointConfig",
    "CosineWarmupSchedulerConfig",
    "EvaluationDataConfig",
    "FewShotConfig",
    "FewShotDataConfig",
    "FewShotResult",
    "LoggingConfig",
    "OptimizerConfig",
    "TrainingConfig",
    "Trainer",
    "build_cosine_warmup_scheduler",
    "build_few_shot_loaders",
    "build_zero_shot_dataloader",
    "evaluate_loop",
    "run_few_shot_adaptation",
    "set_seed",
]
